package com.lonebytesoft.thetaleclient.api.dictionary;

import java.util.HashMap;
import java.util.Map;

/**
 * @author Hamster
 * @since 17.02.2015
 */
public enum CompanionSpecies {

    MECHANICAL_DOG(14, "Механическая собака", CompanionRarity.COMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BRAVE, 40, getFeaturesMap(0, CompanionFeature.FIGHTER, 0, CompanionFeature.SLOW, 0, CompanionFeature.COMPLEX, 33, CompanionFeature.RAM, 66, CompanionFeature.BODYGUARD), "Один из многих «домашних» конструктов – механическая собака. Нет ничего удивительного в том, что магомеханики брали за основу образ всеми любимого животного. Однако полученный результат весьма далёк от ожидаемого: лязгающие, периодически заклинивающиеся механизмы не очень-то похожи на собак, к тому же довольно сложно устроены, что затрудняет их эксплуатацию и ремонт."),
    DWARF_MASTIFF(12, "Дварфский мастиф", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.VALIANT, 50, getFeaturesMap(0, CompanionFeature.HONEST, 0, CompanionFeature.LAZY, 0, CompanionFeature.EATER, 0, CompanionFeature.FIGHTER, 33, CompanionFeature.GOON, 66, CompanionFeature.DEVOURER), "Издалека эту собаку можно принять за медведя. Невероятных размеров пёс с густой тёмно-бурой шерстью имеет грудь, в обхвате почти не уступающей медвежьей, огромную голову с короткой, но смертоносной пастью, толстые мощные лапы, медленный, но уверенный шаг. Горный, так ещё называют эту породу, мастифф был выведен для охраны, охоты и спасательных работ при снежных обвалах. Сложно найти собаку опаснее, сильнее и выносливее, и абсолютно точно не найти породы умней."),
    RAVEN_PERCHERON(40, "Вороной першерон", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 50, getFeaturesMap(0, CompanionFeature.SLED, 0, CompanionFeature.EATER, 33, CompanionFeature.DRAUGHT, 66, CompanionFeature.INDEPENDENT), "Известная повсеместно порода тягловых лошадей заслужила добрую славу. Высокие, с широкой грудью и сильными ногами першероны незаменимы для караванщиков. Вороная же масть, выведенная дварфами – гарантия прекрасной родословной."),
    POLISHED_CHEETAH(18, "Отполированный гепард", CompanionRarity.COMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BRAVE, 30, getFeaturesMap(0, CompanionFeature.FIGHTER, 33, CompanionFeature.BODYGUARD, 66, CompanionFeature.RAM), "Не самая удачная попытка создать полезного конструкта. Тонкий металлический отполированный кот получился быстрым, и это, пожалуй, его единственное достоинство, позволяющее всё же атаковать цель. В остальном это весьма ненадёжный механизм, но, надо признать, достаточно симпатичный."),
    TRAINED_CAT(6, "Дрессированный кот", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.ADVENTURER, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.EATER, 0, CompanionFeature.DEXTEROUS, 0, CompanionFeature.PUNY, 0, CompanionFeature.CUTE, 33, CompanionFeature.INDEPENDENT, 66, CompanionFeature.HAWKEYE), "Довольно редкое явление – дрессированный кот. Кошки плохо поддаются дрессуре, но если всё же удаётся научить кота показывать разные трюки, выполнять команды, то, как правило, зрителям это нравится. Народ умиляется, глядя на забавных животных, и всегда готов подкинуть артисту пару монет на что-нибудь вкусненькое «для милашки»."),
    JAGUAR(17, "Ягуар", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 50, getFeaturesMap(0, CompanionFeature.HONEST, 0, CompanionFeature.LAZY, 0, CompanionFeature.EATER, 0, CompanionFeature.FIGHTER, 33, CompanionFeature.INDEPENDENT, 66, CompanionFeature.GOON), "Этот красивый дикий кот – олицетворение благородства и грации. Мало кому удаётся подчинить себе столь дикого зверя. Но если всё же ягуар начинает слушаться хозяина, привязывается к нему, то счастливому обладателю этого чуда завидуют все."),
    CRAB_EATING_FOX(9, "Майконг", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.HESITANT, 40, getFeaturesMap(0, CompanionFeature.CANNY, 0, CompanionFeature.EATER, 0, CompanionFeature.FIGHTER, 33, CompanionFeature.INDEPENDENT, 66, CompanionFeature.HAWKEYE), "Орки утверждают, что это лиса, некоторые учёные твердят, что майконги – собаки. Как бы там ни было, жители пустынь давно пытаются воспитывать и дрессировать этих животных. Но пока это далеко не всегда удаётся . И всё же многие хотят иметь не просто собаку, а что-нибудь экзотичное, и храбрые, пусть и диковатые, майконги пользуются определённой популярностью."),
    PAPER_STORK(37, "Бумажный аист", CompanionRarity.UNCOMMON, CompanionType.MECH, Archetype.MAGE, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.PIGMEAT, 0, CompanionFeature.PROMPT, 0, CompanionFeature.HAWKEYE, 0, CompanionFeature.FLYER, 50, CompanionFeature.IMPETUOUS), "Стоит ли говорить о хрупкости этого конструкта? Склеенный из ивовых прутиков и бумаги, наделённый весьма слабой магией, аист хорошо выполняет функции наблюдателя, но, увы, недолго. Бумажные птицы столь дёшевы, что порой их покупают, как игрушки для детей, Однако для начинающего ходока, ограниченного в средствах, нет лучшего спутника в дороге."),
    COWRIE_NAG(39, "Каурая кляча", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.VILE, 0, CompanionFeature.PUNY, 0, CompanionFeature.TROTTER, 0, CompanionFeature.EATER, 0, CompanionFeature.COWARD, 33, CompanionFeature.FREIGHT, 66, CompanionFeature.DEXTEROUS), "Ничем не примечательная лошадь. Она неприхотлива, сообразительна. Учитывая цену на это верховое животное, пугливость каурой клячи сложно рассматривать как серьёзный недостаток."),
    COMPOSITE_HEAVY_HORSE(41, "Композитный битюг", CompanionRarity.UNCOMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.VALIANT, 70, getFeaturesMap(0, CompanionFeature.HULKY, 0, CompanionFeature.SLED, 0, CompanionFeature.NOISY, 33, CompanionFeature.DRAUGHT, 66, CompanionFeature.RAM), "Очень надёжный, прочный и грузоподъёмный конструкт. Устройство его таково, что большинство деталей можно делать из разных металлов и даже древесины, поэтому не бывает двух одинаковых композитных битюгов. Эти лошади, как правило, выглядят пёстро и очень разнообразно, что добавляет им некоторой привлекательности."),
    TRAINED_CARACAL(20, "Дрессированный каракал", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 30, getFeaturesMap(0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.CAMOUFLAGE, 0, CompanionFeature.EATER, 0, CompanionFeature.FIGHTER, 33, CompanionFeature.INDEPENDENT, 66, CompanionFeature.DEVOURER), "Только немногие мастера, орки и люди, способны дрессировать этих диких кошек. Секрет воспитания передаётся из поколения в поколение и тщательно оберегается. Но результат, как правило, превосходит все ожидания: красавцы каракалы становятся очень послушными и готовы отдать жизнь за своего хозяина."),
    FRAGILE_LION(23, "Хрупкий лев", CompanionRarity.COMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BRAVE, 30, getFeaturesMap(0, CompanionFeature.FEARFUL, 0, CompanionFeature.GOON, 0, CompanionFeature.SPARE_PARTS, 33, CompanionFeature.RAM, 66, CompanionFeature.BODYGUARD), "Своеобразный, жутковато выглядящий конструкт. Недолговечен из-за подбора материалов, из которых создан, и всё же он очень и очень неплох в деле. Хрупкость каркаса льва полностью компенсируется его мощными лапами и острыми зубами, которыми этот кот может уничтожить почти любого противника. Конструкт непопулярен, но тот, кто знает толк в боях, всегда оценит опасность соперника, обладающего этим смертоносным магомеханизмом."),
    SHAGGY_DOG(10, "Лохматый пёс", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 30, getFeaturesMap(0, CompanionFeature.CANNY, 0, CompanionFeature.PEACEFUL, 0, CompanionFeature.COWARD, 0, CompanionFeature.LAZY, 0, CompanionFeature.INDEPENDENT, 0, CompanionFeature.EATER, 33, CompanionFeature.FIGHTER, 66, CompanionFeature.HAWKEYE), "Беспородные собаки есть в каждой деревне, кроме эльфийской, разумеется. Умные, преданные, отлично дрессируемые собаки навсегда останутся лучшими друзьями и дома, и в путешествии."),
    ORC_HOUND(13, "Орочья гончая", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 40, getFeaturesMap(0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.EATER, 0, CompanionFeature.LAZY, 0, CompanionFeature.FIGHTER, 0, CompanionFeature.DEXTEROUS, 33, CompanionFeature.HAWKEYE, 66, CompanionFeature.BODYGUARD), "Орочья гончая весьма популярна у охотников и отличается легкостью в разведении.У этой породы множество достоинств: ум, преданность хозяину, длинные быстрые лапы, превосходный нюх. Стоит также отметить невысокую цену, которую орки-заводчики просят за рыжих с подпалинами щенков."),
    ALBINO_PANTHER(30, "Пантера-альбинос", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BRAVE, 50, getFeaturesMap(0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.GLUTTONOUS, 0, CompanionFeature.FEARFUL, 0, CompanionFeature.HAWKEYE, 0, CompanionFeature.IMPETUOUS, 25, CompanionFeature.FIGHTER, 50, CompanionFeature.BODYGUARD, 75, CompanionFeature.GOON), "Нет сомнения, что пантера-альбинос – один из самых редких зверей во всей Пандоре. Огромная белоснежная кошка с пугающими красными глазами обладает агрессивным и своенравным характером. При этом она очень легко привязывается к хозяину, и, как утверждают специалисты, сложно найти более преданного спутника. Этот факт в сочетании с выдающейся силой, чутким слухом и прекрасным ночным зрением делает пантеру-альбиноса завидным помощником любому искателю приключений."),
    OCELOT_CONSTRUCT(22, "Оцелот-конструкт", CompanionRarity.UNCOMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.VALIANT, 30, getFeaturesMap(0, CompanionFeature.FIGHTER, 0, CompanionFeature.EXPENSIVE, 0, CompanionFeature.GNAWER, 0, CompanionFeature.COMPLEX, 33, CompanionFeature.GOON, 66, CompanionFeature.RAM), "Дикие кошки, пожалуй, самые частые вдохновители магомехаников. Силу и грацию этих мистических животных крайне редко удаётся передать механизмам, но в случае с оцелотом-конструктом мы видим превосходный результат. Невысокая прочность – единственный недостаток, легко компенсируемый скоростью, мощностью и надёжностью исполнения вложенных охранных задач."),
    STEEL_FOX(15, "Стальная лиса", CompanionRarity.UNCOMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BOLD, 40, getFeaturesMap(0, CompanionFeature.PACK, 0, CompanionFeature.DEXTEROUS, 33, CompanionFeature.BODYGUARD, 66, CompanionFeature.FIGHTER), "Один из самых популярных и элегантных конструктов. Весьма удобен в эксплуатации, с ним редко возникают проблемы технического характера, но это не самый сильный помощник в бою. Стальную лису редко можно встретить в продаже – их изготавливают лучшие магомеханики и только на заказ."),
    POISONOUS_LYNX(19, "Рысь-ядомор", CompanionRarity.COMMON, CompanionType.MECH, Archetype.ADVENTURER, CompanionDedication.BRAVE, 30, getFeaturesMap(0, CompanionFeature.POISONER, 0, CompanionFeature.SPARE_PARTS, 0, CompanionFeature.EXPENSIVE, 33, CompanionFeature.FIGHTER, 66, CompanionFeature.RAM), "Весьма интересный механический помощник. Конструкт создаётся с использованием дорогостоящей магии, которая делает когти стальной рыси отравленными. Очень популярен у героев и прочих искателей приключений. Немаловажно, что в случае его поломки всегда можно выгодно продать запчасти."),
    SPARKLING_ONCILLA(32, "Сверкающая онцилла", CompanionRarity.UNCOMMON, CompanionType.UNCOMMON, Archetype.ADVENTURER, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.STUBBORN, 0, CompanionFeature.CANNY, 0, CompanionFeature.DISCREET, 0, CompanionFeature.FIGHTER, 25, CompanionFeature.SPIRIT_CONTACT, 50, CompanionFeature.WORSHIPPER, 75, CompanionFeature.BODYGUARD), "Мелкая бестелесная кошка. Её не перепутать с обычным хищником благодаря искрящейся шерсти, сверкающей даже при свете дня. Если коснуться этого существа, то рука пройдёт сквозь тело онциллы, не встретив препятствия. Такие создания очень непослушны, но всё же могут принести немалую пользу своему хозяину, магически атакуя его противников."),
    CLAY_BLACK_BEAR(33, "Глиняный барибал", CompanionRarity.COMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.VALIANT, 50, getFeaturesMap(0, CompanionFeature.CLUMSY, 0, CompanionFeature.RAM, 50, CompanionFeature.GOON), "Медведь барибал – сам по себе опасный хищник, и уж тем более опасен конструкт, созданный по его образу и подобию, но не чувствующий ни боли, ни страха. Конечно, глина – один из самых непрочных материалов для создания магомеханических спутников, однако данный проект оказался успешным, а полученные экземпляры весьма надёжными и функциональными."),
    FIGHTER_MERCENARY(8, "Воин-наёмник", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BRAVE, 40, getFeaturesMap(0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.DEXTEROUS, 0, CompanionFeature.GLUTTONOUS, 0, CompanionFeature.FIGHTER, 25, CompanionFeature.PACK, 50, CompanionFeature.DRUNKARD, 75, CompanionFeature.GOON), "В Пандоре много наёмников. Среди них встречаются как новички, так и матёрые ветераны. Последних, конечно же, немного и все они, за редким исключением, состоят на уважаемой службе: охраняют советников, поддерживают безопасность на трактах. Но порой всё же можно увидеть настоящего воина-наёмника в компании с героем-ходоком. Эти бродяги иногда тоже готовы платить за помощь."),
    TAMED_COUGAR(27, "Ручной кугуар", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BRAVE, 30, getFeaturesMap(0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.EATER, 0, CompanionFeature.CAMOUFLAGE, 0, CompanionFeature.DEXTEROUS, 0, CompanionFeature.HAWKEYE, 50, CompanionFeature.FIGHTER), "Этот редкий вид пумы обитает в тёплых невысоких горах и предгорьях. Кугуары редко нападают на путников, так как не выходят к трактам и поселениям, при этом они удивительно легко приручаются. Рыжие кошки хоть и не выделяются размерами или силой, но довольно агрессивны. Они стали бы, вероятно, крайне популярными спутниками многих героев, если бы встречались в природе чаще. Но, к сожалению, численность их невелика, а размножение в неволе пока не имеет успеха."),
    WHITE_BEAR(34, "Белый медведь", CompanionRarity.RARE, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 70, getFeaturesMap(0, CompanionFeature.FIGHTER, 0, CompanionFeature.FEARFUL, 0, CompanionFeature.GLUTTONOUS, 0, CompanionFeature.GNAWER, 20, CompanionFeature.DEVOURER, 40, CompanionFeature.GOON, 60, CompanionFeature.INDEPENDENT, 80, CompanionFeature.RAM), "Один из самых редких медведей, как живых, так и механических. Этот огромный зверь обитает на далёком севере, повстречать его крайне сложно. Белый медведь – страшный и могучий хищник, умный, выносливый и неприхотливый. Тот, кто сумеет с ним подружиться, получит непревзойдённого помощника."),
    PIEBALD_NAG(38, "Пегая кляча", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 30, getFeaturesMap(0, CompanionFeature.PEACEFUL, 0, CompanionFeature.LAZY, 0, CompanionFeature.SLED, 0, CompanionFeature.EATER, 0, CompanionFeature.PIGMEAT, 33, CompanionFeature.PACK, 66, CompanionFeature.INDEPENDENT), "В мире много лошадей, дорогих и не очень, скаковых и упряжных, но есть и такие, которые всем знакомы, их не спутаешь ни с какой другой. Самая обычная лошадь, имеющаяся в любом поселении – это пегая кляча. У этого животного всего понемногу и всё в меру: стать, выносливость, престиж и… цена."),
    CLAY_LEOPARD(31, "Глиняный барс", CompanionRarity.RARE, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BRAVE, 50, getFeaturesMap(0, CompanionFeature.COMPLEX, 0, CompanionFeature.FIGHTER, 50, CompanionFeature.RAM), "Глиняный барс весьма распространён по всей Пандоре. По большому счёту этот конструкт весьма хорош, но трудно выделить какие-то характерные именно для него положительные качества. Средней полезности помощник для средних по сложности дел, однако, крупный хищник, пусть и изготовленный из дешёвой глины, смотрится прекрасно и создаёт неплохой имидж хозяину."),
    GINGER_TROTTER(42, "Игреневый рысак", CompanionRarity.RARE, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BRAVE, 50, getFeaturesMap(0, CompanionFeature.PEACEFUL, 0, CompanionFeature.PACK, 0, CompanionFeature.EATER, 0, CompanionFeature.RARE, 33, CompanionFeature.LIGHTFOOTED, 66, CompanionFeature.INDEPENDENT), "Прекрасной породы и красивой масти конь один из лучших спутников любому герою. Игреневые рысаки ценятся по всей Пандоре за миролюбивый нрав и скорость. У этих скакунов длинные ноги, тонкая шея и лёгкий бег, а также, что очень важно для путешественников, они не пугливы и не впадают в панику даже при виде хищника."),
    FOG_WOLF(16, "Туманный волк", CompanionRarity.RARE, CompanionType.UNCOMMON, Archetype.MAGE, CompanionDedication.BRAVE, 60, getFeaturesMap(0, CompanionFeature.OBSTINATE, 0, CompanionFeature.VILE, 0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.WORSHIPPER, 25, CompanionFeature.FIGHTER, 50, CompanionFeature.REGENERATION, 75, CompanionFeature.INSPIRATION), "Посланник из мира Хранителей. Весьма своенравное создание, будто сотканное из тумана, чуть светящегося во тьме. Быстрый, колдовской, с горящими жёлтыми глазами туманный волк вызывает уважение к своему обладателю."),
    COMPLEX_LEOPARD(24, "Мудрёный леопард", CompanionRarity.RARE, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.HESITANT, 50, getFeaturesMap(0, CompanionFeature.COMPLEX, 0, CompanionFeature.FIGHTER, 50, CompanionFeature.GOON), "Яркий пример того, как конструкт “не получился”. Создатели этого тяжёлого металлического хищника наверняка хотели достичь совершенно иного результата, но, как говорится, перемудрили. В итоге получился крепкий, мощный, но очень сложный в управлении и ремонте конструкт-охранник. Впрочем, производитель готов продавать своё творение по весьма сходной цене."),
    WHITE_TIGER(26, "Белый тигр", CompanionRarity.EPIC, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.HEROIC, 70, getFeaturesMap(0, CompanionFeature.HONEST, 0, CompanionFeature.DISCREET, 0, CompanionFeature.GLUTTONOUS, 0, CompanionFeature.GOON, 0, CompanionFeature.CAMOUFLAGE, 20, CompanionFeature.INDEPENDENT, 40, CompanionFeature.RAM, 60, CompanionFeature.DEVOURER, 80, CompanionFeature.BODYGUARD), "Многие мечтают хотя бы просто увидеть белого тигра – одну из легенд Пандоры. Счастливец тот, кто сможет стать другом этому могучему и прекрасному зверю, воплотившему в себе дух свободы и благородства. Белый тигр крупнее своих сородичей, его очень сложно повстречать и почти невозможно подчинить."),
    SLOW_BEAR(36, "Медлительный кадьяк", CompanionRarity.EPIC, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BRAVE, 60, getFeaturesMap(0, CompanionFeature.COMPLEX, 0, CompanionFeature.EXPENSIVE, 0, CompanionFeature.FIGHTER, 0, CompanionFeature.SLOW, 33, CompanionFeature.RAM, 66, CompanionFeature.GOON), "Дорогостоящий, сложно устроенный конструкт, хороший помощник в приключениях. Он силён и послушен, внушительно выглядит. И всё же многие скажут, что этот металлический медведь “на любителя”, ведь у него есть существенный недостаток – медлительность, и нередкие задержки в пути немного портят репутацию кадьяка."),
    BLACK_CAT(7, "Чёрная кошка", CompanionRarity.RARE, CompanionType.ALIVE, Archetype.ADVENTURER, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.STUBBORN, 0, CompanionFeature.EATER, 0, CompanionFeature.CHARMING, 0, CompanionFeature.IMPETUOUS, 0, CompanionFeature.COWARD, 25, CompanionFeature.HAWKEYE, 50, CompanionFeature.SPIRIT_CONTACT, 75, CompanionFeature.INDEPENDENT), "Чёрным кошкам все расы во все времена приписывают необычные свойства. Ничего удивительного, в них и правда есть что-то мистическое. Стоит заглянуть в опаловые глаза, и становится ясно: они видят то, что нам не дано узреть никогда. Когда ты смотришь на чёрную кошку, знай – ей известно большее, гораздо большее, нежели нам."),
    EARED_SERVAL(21, "Ушастый сервал", CompanionRarity.RARE, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.VALIANT, 50, getFeaturesMap(0, CompanionFeature.PACK, 0, CompanionFeature.DEXTEROUS, 33, CompanionFeature.RAM, 66, CompanionFeature.FIGHTER), "Конструкт, что называется, на любителя. Многим нравится его внешний вид, очень напоминающий живого кота. Ценят также надёжность механизма, удивительную при столь небольших размерах. Ушастых сервалов сложно приобрести, их изготавливают в незначительных количествах. Это чудо магомеханики всегда легко узнать по длинным лапам и обязательным большим ушам, несущим сугубо декоративное назначение."),
    REINDEER(5, "Северный олень", CompanionRarity.LEGENDARY, CompanionType.ALIVE, Archetype.MAGE, CompanionDedication.BRAVE, 60, getFeaturesMap(0, CompanionFeature.CONSCIENTIOUS, 0, CompanionFeature.EATER, 0, CompanionFeature.TROTTER, 0, CompanionFeature.SPECIAL, 20, CompanionFeature.INDEPENDENT, 40, CompanionFeature.SPIRIT_CONTACT, 60, CompanionFeature.PACK, 80, CompanionFeature.INSPIRATION), "Северный олень – красивое и гордое животное. Он никогда и никому не покоряется. Есть, конечно, слухи об орках кочевниках, живущих в снежных пустынях и сумевших приручить оленей, но это не более, чем слухи. Северный олень – достаточно большой, чтобы возить орка на спине, совершенно дикий и своенравный зверь."),
    ASTRAL_PANTHER(29, "Астральная пантера", CompanionRarity.LEGENDARY, CompanionType.UNCOMMON, Archetype.ADVENTURER, CompanionDedication.HESITANT, 60, getFeaturesMap(0, CompanionFeature.PROMPT, 0, CompanionFeature.HONEST, 0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.WORSHIPPER, 20, CompanionFeature.GOON, 40, CompanionFeature.REGENERATION, 60, CompanionFeature.ENERGETIC, 80, CompanionFeature.RAM), "Прозрачно-чёрная, словно вылитая из дорогого стекла; стремительная, но неторопливая; агрессивная, но полностью послушная – астральная пантера грациозна и великолепна, она истинный дар Хранителя своему подопечному. Этот благородный волшебный зверь – прекрасный и верный спутник героя."),
    VILLAGE_BLACKSMITH(1, "Деревенский кузнец", CompanionRarity.LEGENDARY, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 40, getFeaturesMap(0, CompanionFeature.FIGHTER, 0, CompanionFeature.SPECIAL, 0, CompanionFeature.DRUNKARD, 0, CompanionFeature.EATER, 33, CompanionFeature.PACK, 66, CompanionFeature.GOON), "Деревенские – народ крепкий, а уж кузнецы и подавно. Крепкие, сухие, выносливые мастера скобяных дел, если их разозлить, могут быть весьма опасны. Удар кузнечного молота, на наковальне правящий металл, с телом врага способен сотворить чистое месиво. К тому же, не стоит забывать, что некоторые кузнецы делают оружие и порой неплохо этим оружием владеют."),
    GREY_PUMA(25, "Серая пума", CompanionRarity.EPIC, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.VALIANT, 50, getFeaturesMap(0, CompanionFeature.LAZY, 0, CompanionFeature.EATER, 0, CompanionFeature.IMPETUOUS, 0, CompanionFeature.FIGHTER, 20, CompanionFeature.HAWKEYE, 40, CompanionFeature.DEVOURER, 60, CompanionFeature.GOON, 80, CompanionFeature.INDEPENDENT), "Редкий вид дикой горной кошки. Этот опасный хищник обладает великолепным слухом и зрением и предупредит хозяина об опасности, правда, если захочет. Собственно, непокорность серой пумы – главный аргумент противников приручения этих животных."),
    WOLFHOUND(11, "Волкодав", CompanionRarity.LEGENDARY, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.VALIANT, 60, getFeaturesMap(0, CompanionFeature.CONSCIENTIOUS, 0, CompanionFeature.FEARFUL, 0, CompanionFeature.EATER, 0, CompanionFeature.HAWKEYE, 0, CompanionFeature.DEXTEROUS, 25, CompanionFeature.FIGHTER, 50, CompanionFeature.INDEPENDENT, 75, CompanionFeature.SPIRIT_CONTACT), "Волкодавы – это особенные собаки. Серые лохматые псы, огромные и страшные, обладают мощными челюстями, острым слухом и полным, абсолютным бесстрашием. Их вывели у людей для охраны скота от волков, но порода уже давным-давно пользуется популярностью повсюду. Волкодавы охраняют дворы, караваны, детей и склады. Это поистине уникальные и незаменимые собаки."),
    PALADIN(4, "Паладин", CompanionRarity.LEGENDARY, CompanionType.ALIVE, Archetype.ADVENTURER, CompanionDedication.BRAVE, 50, getFeaturesMap(0, CompanionFeature.GOON, 0, CompanionFeature.EATER, 0, CompanionFeature.SPECIAL, 25, CompanionFeature.HEALER, 50, CompanionFeature.WORSHIPPER, 75, CompanionFeature.EXORCIST), "Есть много способов служения Богам, и один из них – вступить в какой-нибудь орден паладинов, чтущих Добро и Порядок. Эти воинствующие священники по мере сил, порой весьма внушительных, истребляют нежить, демонов и прочие порождения Тьмы... К сожалению, они не столь крепки, как герои-ходоки, и потому живут недолго... Но ярко!"),
    SUMMONED_FOSSA(28, "Призванная фосса", CompanionRarity.LEGENDARY, CompanionType.UNCOMMON, Archetype.MAGE, CompanionDedication.BOLD, 60, getFeaturesMap(0, CompanionFeature.VILE, 0, CompanionFeature.PEACEFUL, 0, CompanionFeature.SPIRIT_CONTACT, 0, CompanionFeature.CAMOUFLAGE, 20, CompanionFeature.FIGHTER, 40, CompanionFeature.HAWKEYE, 60, CompanionFeature.PEP, 80, CompanionFeature.BODYGUARD), "У фоссы, мелкого хищника, имеется двойник в нематериальном мире. Это существо магического происхождения может оказать большую помощь своему обладателю благодаря изрядной хитрости и особой связи с Хранителем. Призванная фосса крупнее живого прообраза, гораздо умнее его и обладает подлыми повадками. При этом она до конца готова защищать хозяина, не чувствуя ни страха, ни боли."),
    ORPHAN(2, "Сиротинушка", CompanionRarity.LEGENDARY, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.STUBBORN, 0, CompanionFeature.CUTE, 0, CompanionFeature.PUNY, 0, CompanionFeature.GLUTTONOUS, 0, CompanionFeature.SPECIAL, 33, CompanionFeature.PICKPOCKET, 66, CompanionFeature.PACK), "В деревне нередко можно встретить детей-сирот, которым помогают кто чем может. Таких ребят зовут почти ласково – сиротинушка. Они не столь сильно обижены на мир, как городские беспризорники, но всё же некоторые мечтают уйти из деревни... Только вот редко кто берёт их с собой."),
    TEMPLE_GUARD(3, "Храмовый страж", CompanionRarity.LEGENDARY, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BOLD, 50, getFeaturesMap(0, CompanionFeature.COMPLEX, 0, CompanionFeature.FIGHTER, 0, CompanionFeature.FEARFUL, 0, CompanionFeature.EXPENSIVE, 0, CompanionFeature.SPECIAL, 33, CompanionFeature.BODYGUARD, 66, CompanionFeature.RAM), "У служителей различных храмов свои тайны, которые они ревностно стерегут, в чём им помогают не только шпионы, воины и деньги. Храмовники вполне успешно используют магию, в том числе магомеханизмы. Один из таких наиболее редких и легендарных конструктов – храмовый страж. Он является изобретением поклонников некоего доброго божества. Это мощный и крайне опасный боевой магомеханизм, вооружённый двумя булавами и осадным арбалетом, вмонтированным в стальной корпус. В целом же храмовый страж напоминает металлическую курицу ростом с гоблина."),
    GOLD_BEAR(35, "Золотой шатун", CompanionRarity.LEGENDARY, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.VALIANT, 40, getFeaturesMap(0, CompanionFeature.COMPLEX, 0, CompanionFeature.EXPENSIVE, 0, CompanionFeature.GOON, 0, CompanionFeature.VERY_RARE, 25, CompanionFeature.PACK, 50, CompanionFeature.RAM, 75, CompanionFeature.SLED), "Пожалуй, самый претенциозный из всех возможных конструктов. Груда золота и золочёной стали, имеющая форму медведя с огромными когтями, конечно же, внушает трепет и уважение, но при этом вызывает странное чувство. Золото – не самый прочный металл, да и драгоценные камни глаз многим кажутся излишеством, ведь подошёл бы и простой горный хрусталь. И уж совсем необычно выглядит на спине у конструкта инкрустированное золотом седло, которое крепят некоторые умельцы."),
    ETHEREAL_SERVANT(53, "Бестелесный слуга", CompanionRarity.UNCOMMON, CompanionType.UNCOMMON, Archetype.MAGE, CompanionDedication.BOLD, 50, getFeaturesMap(0, CompanionFeature.FREIGHT, 50, CompanionFeature.HAWKEYE), "Посредством несложной магии возможно создать почти невидимого слугу. Такой фантом, сотканный из волшебных энергий и не имеющий тела, не способен выполнять сложные приказы, но вполне годен для переноса багажа."),
    PAUPER_PHILOSOPHER(43, "Нищий философ", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.MAGE, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.CANNY, 0, CompanionFeature.DISCREET, 0, CompanionFeature.DRUNKARD, 0, CompanionFeature.EATER, 0, CompanionFeature.CLUMSY, 0, CompanionFeature.WISE, 33, CompanionFeature.ROBBER, 66, CompanionFeature.PACK), "Хороший алхимик или врач всегда найдут подходящую работу, но философы никому не нужны. Мир суров, его жители вынужденны бороться то за урожай, то за жизнь, то с засухой, то с наводнением, им не до рассуждений о гуманизме и смыслах бытия. Вот и бродят порой по Пандоре или попрошайничают в городах нищие философы, разочарованные в жизни, без семьи и веры в справедливость."),
    SAGE(47, "Мудрец", CompanionRarity.RARE, CompanionType.ALIVE, Archetype.ADVENTURER, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.PROMPT, 0, CompanionFeature.EATER, 0, CompanionFeature.HULKY, 0, CompanionFeature.WISE, 25, CompanionFeature.PACK, 50, CompanionFeature.HEALER, 75, CompanionFeature.FAMOUS), "Миру нужны мудрецы, но их всегда не хватает. Собиратели накопленного разумом , исследователи нашей души, рыцари науки странствуют по миру в поисках новых знаний, рискуют своей жизнью, являясь лёгкой мишенью для негодяев и монстров всех мастей. Их беззаветное стремление к поиску ответов на все вопросы порой приводит к гибели. Поэтому каждый уважающий себя герой должен помогать им, охраняя на трактах и набираясь при этом мудрости."),
    ASTRAL_REFLECTION(52, "Астральное отражение", CompanionRarity.LEGENDARY, CompanionType.UNCOMMON, Archetype.MAGE, CompanionDedication.VALIANT, 70, getFeaturesMap(0, CompanionFeature.PROMPT, 0, CompanionFeature.FIGHTER, 0, CompanionFeature.FEARFUL, 33, CompanionFeature.SPIRIT_CONTACT, 66, CompanionFeature.GOON), "Это случается очень редко: Духи-хранители посылают героям в помощь их астральное отражение. Такой спутник выглядит как состоящая из плотного тумана точная копия хозяина, цвета одежды у него блеклые, будто выгоревшие. Существо отлично помогает в бою, но из-за своей внешности и странной чуждой ауры, ощутимой вблизи, может создавать хозяину проблемы в общении с окружающими."),
    MAGE_MERCENARY(44, "Маг-наёмник", CompanionRarity.RARE, CompanionType.ALIVE, Archetype.MAGE, CompanionDedication.BOLD, 30, getFeaturesMap(0, CompanionFeature.EATER, 0, CompanionFeature.CLUMSY, 0, CompanionFeature.ARSONIST, 25, CompanionFeature.FREEZER, 50, CompanionFeature.TELEPORTER, 75, CompanionFeature.POISONER), "Кого только не встретишь на трактах Пандоры. Порой в путешествия отправляются маги, покидая свои башни и лаборатории. Их тянет в путь разное. Кого скука, кого желание прославиться, если это не удаётся дома. И у тех, и у других нередко заканчиваются финансы, и тогда им приходится искать работу и пропитание. Некоторые идут в помощники к опытным магам, а иные прибиваются к героям или нанимаются в охрану караванов и связывают свою жизнь с риском и приключениями. Такой спутник может быть очень полезен в пути."),
    MUKRED(49, "Мукред", CompanionRarity.LEGENDARY, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BRAVE, 60, getFeaturesMap(0, CompanionFeature.TROTTER, 20, CompanionFeature.FIGHTER, 40, CompanionFeature.FREIGHT, 60, CompanionFeature.RAM, 80, CompanionFeature.GOON), "Мукред – необычный конструкт широкого спектра применения. Откуда такое название, точно неизвестно, но существуют две основные версии. Согласно первой, у создателей конструкта, двух близнецов-гоблинов, был пёсик по кличке Мукред. Вторая версия утверждает, что мукред – аббревиатура, а полное название магомеханизма – многофункциональный улучшенный конструкт разработанный Еном и Дуонгом. Впрочем, обладателей конструкта мало беспокоит, которая из версий правдива. Куда важнее для всех то, как мукред выглядит и что он может, и вот тут есть, о чём рассказать. Сначала представьте себе два огромных таза: один накрывает другой. Затем добавьте вращающуюся по кругу в щели между ними острую пилу. В довершении дорисуйте закрепленное сверху конструкции неудобное, но прочное кресло, а также крюки для подвешивания груза. Двигается вся эта стальная экзотика быстро и довольно тихо, на четырёх коротких многосуставных лапах."),
    WANDERING_SORCERER(46, "Бродячий колдун", CompanionRarity.EPIC, CompanionType.ALIVE, Archetype.MAGE, CompanionDedication.BOLD, 40, getFeaturesMap(0, CompanionFeature.CANNY, 0, CompanionFeature.DISCREET, 0, CompanionFeature.EATER, 0, CompanionFeature.FREEZER, 25, CompanionFeature.WISE, 50, CompanionFeature.TELEPORTER, 75, CompanionFeature.ARSONIST), "Не каждый будет ценить способность к магии. Кто-то будет развивать её, учением и трудом постигая сложнейшую науку, а кто-то удовольствуется природными данными и пойдёт по другому пути – станет бродячим колдуном. Каждому своё. Кто-то получит известность, богатство и уважение сограждан. А кто-то всю жизнь проведёт в дороге, нанимаясь спутником к караванщикам или героям-ходокам, но не испортит драгоценное здоровье в сырых и холодных лабораториях, вдыхая едкую пыль старых фолиантов. Давно подмечено, что бродячие колдуны имеют весьма посредственные магические способности, но более крепки и живучи, чем их учёные собратья."),
    LINKED_PIGGY(54, "Клёпанная свинка", CompanionRarity.COMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.HESITANT, 60, getFeaturesMap(0, CompanionFeature.PROMPT, 0, CompanionFeature.SLOW, 0, CompanionFeature.FREIGHT, 0, CompanionFeature.NOISY, 0, CompanionFeature.CLUMSY, 50, CompanionFeature.RAM), "Впервые такой конструкт был создан для развлечения дочери богатого аристократа. Будучи размером с обычную свинью, украшенную красивыми заклёпками, механизм имеет на спине крышку, подобную крышке сундука. Внутри конструкта довольно много свободного места. Девушка хранила в свинке своих кукол, которых та приносила по приказу хозяйки. Давно уж нет ни тех кукол, ни той аристократической фамилии, а эти забавные конструкты ещё встречаются. Единственное новшество, которым обзавелась магомеханическая свинья – магический замок на крышке, для пущей сохранности имущества. Но по традиции даже заклёпки неизменно делаются в виде цветочков, а копытца свинки при беге издают мелодичный звон."),
    RUNAWAY_CONVICT(45, "Беглый каторжник", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.VILE, 0, CompanionFeature.PEACEFUL, 0, CompanionFeature.EATER, 0, CompanionFeature.DRUNKARD, 0, CompanionFeature.FREIGHT, 0, CompanionFeature.CAD, 33, CompanionFeature.FIGHTER, 66, CompanionFeature.PICKPOCKET), "Если есть цивилизация, то есть законы. Если есть законы, то есть преступники. Если есть преступники, то есть каторга. Если есть умирающие на каторге, то есть и те, кто с неё бежит. Их, беглецов, может остановить арбалетный болт в спину, но кое-кому всё-таки удаётся скрыться от погони. Беглому каторжнику приходится искать еду, деньги, ему нужно поскорее убраться куда-нибудь подальше от окрестностей каторги. Это очень трудно, ведь природа Пандоры смертельно опасна, и некоторые беглецы просят помощи у странствующих героев. Те часто соглашаются на компанию в дороге, чтобы было хоть с кем-то поболтать."),
    UNURAS_SCORPION(50, "Скорпион Унура", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.VALIANT, 50, getFeaturesMap(0, CompanionFeature.EATER, 0, CompanionFeature.POISONER, 25, CompanionFeature.SLED, 50, CompanionFeature.FIGHTER, 75, CompanionFeature.PACK), "Несомненно, одни из самых непригодных существ для воспитания спутников – это насекомые, пауки и им подобные. Но и здесь нашла своё применение магия. Орк Унур, малоизвестный при жизни шаман, вывел удивительную породу скорпионов. Скорпион Унура был обнаружен уже после смерти шамана и назван в его честь. Эти создания сильно отличаются от скорпионов, живущих в дикой природе: они гораздо крупнее и сильнее, но медлительны, что крайне осложняет им охоту и пропитание. Долгое время не удавалось понять, с какой целью Унур вывел этих скорпионов, потратив огромные усилия, пока в одном из городов не был пойман мародёр, пытавшийся продать странное седло. Выяснилось, что преступник ограбил жилище Унура сразу после смерти шамана и унёс всё, что смог, и седло в том числе. Невероятная догадка быстро подтвердилась – скорпионы Унура ездовые. Они плохо размножаются, не столь ядовиты, как обычные, но поддаются дрессировке и отлично себя чувствуют под седлом, надо заметить, весьма удобным для длительных путешествий благодаря широкой спинке и подлокотникам."),
    PHANTOM_ASSISTANT(48, "Фантом-помощник", CompanionRarity.EPIC, CompanionType.UNCOMMON, Archetype.MAGE, CompanionDedication.VALIANT, 40, getFeaturesMap(0, CompanionFeature.ENERGETIC, 0, CompanionFeature.PEP, 25, CompanionFeature.SPIRIT_CONTACT, 50, CompanionFeature.PACK, 75, CompanionFeature.BODYGUARD), "Прекрасный спутник для любого странствующего героя – посланный Хранителем фантом-помощник, объёмная белая тень хозяина. Он ценится не столь, как тягловая сила при переноске грузов, сколько за возможность духовной связи с Хранителем и за энергетическую подпитку в бою."),
    FAIRY(51, "Феечка", CompanionRarity.LEGENDARY, CompanionType.UNCOMMON, Archetype.MAGE, CompanionDedication.BRAVE, 30, getFeaturesMap(0, CompanionFeature.CUTE, 0, CompanionFeature.PIGMEAT, 0, CompanionFeature.WISE, 16, CompanionFeature.HEALER, 32, CompanionFeature.PRAYER, 48, CompanionFeature.INSPIRATION, 64, CompanionFeature.TELEPORTER, 80, CompanionFeature.SPIRIT_CONTACT), "Одно из самых удивительных созданий на свете – фея, миниатюрная эльфка в две ладони ростом и с яркими крылышками бабочки за спиной. В сказках феечки очень добрые создания, но в жизни всё иначе: они, как правило, флегматичны и не испытывают к остальным существам ярких чувств, ни положительных, ни отрицательных, любят только волшебные цветы аппомы, в бутонах которых живут. Однако, иногда феи находят что-то привлекательное для себя в тех, кому покровительствуют Духи-хранители, таких героев можно назвать счастливчиками."),
    FAKIR(68, "Факир", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.MAGE, CompanionDedication.BOLD, 30, getFeaturesMap(0, CompanionFeature.HONEST, 0, CompanionFeature.PEACEFUL, 0, CompanionFeature.EATER, 0, CompanionFeature.ARSONIST, 50, CompanionFeature.PACK), "На каждой ярмарке можно встретить факиров. Магия ли лежит в основе их искусства или годы тренировок, какое это имеет значение для неискушённого зрителя? А в промежутках между ярмарками факиры блуждают по пандорским трактам в компаниях с героями-ходоками. Если один из спутников умеет ловко орудовать мечом, а второй прицельно плюётся горящим маслом, то эта парочка с удовольствием предоставит массу неудобств любому, кто захочет облегчить их кошельки."),
    TRAINED_MARMOSET(75, "Дрессированная мартышка", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BRAVE, 30, getFeaturesMap(0, CompanionFeature.PEACEFUL, 0, CompanionFeature.EATER, 0, CompanionFeature.HAWKEYE, 0, CompanionFeature.LAZY, 50, CompanionFeature.ROBBER), "Популярная среди ходоков и бродячих артистов обезьяна-мартышка. Она способна выучить пару простых трюков, но не слишком умна. Бесспорным плюсом дрессированных мартышек является их послушность. В бою такой спутник является более помехой, чем помощью, но герои ценят ласку и природную жизнерадостность этих зверушек, скрашивающие тяготы пути. У мартышек прекрасный слух, поэтому, останавливаясь на ночлег, герой всегда может быть уверенным, что при малейшей опасности обезьянка разбудит его громким визгом."),
    PHANTOM_SECURITY(56, "Охранник-фантом", CompanionRarity.COMMON, CompanionType.UNCOMMON, Archetype.MAGE, CompanionDedication.HEROIC, 70, getFeaturesMap(0, CompanionFeature.PIGMEAT, 0, CompanionFeature.BODYGUARD, 50, CompanionFeature.FIGHTER), "Тем, кто не любит компанию надоедающих болтовней наёмников, скрежет ржавеющих конструктов и вечный запах от животных, прекрасно подойдёт в дороге охранник-фантом. Хоть и недолговечный, но всегда готовый принять вместо хозяина смертельный удар, магический помощник внешне напоминает мыльный пузырь в форме большой обезьяны или уродливого гоблина."),
    SLINGER(71, "Пращник", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BRAVE, 40, getFeaturesMap(0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.FIGHTER, 0, CompanionFeature.EATER, 50, CompanionFeature.PACK), "Праща – оружие не слишком-то серьёзное и встречается редко, тем не менее некоторые наёмники пользуются ими весьма успешно. Особенно действенной бывает праща при нападении чудовища большого размера: мощный удар издалека позволит оглушить противника и поможет спутнику в ближнем бою прикончить врага. Пожалуй, главным достоинством этого нехитрого приспособления для убийства является то, что снаряды буквально валяются под ногами."),
    RESEARCHER(70, "Исследователь", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.ADVENTURER, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.PROMPT, 0, CompanionFeature.PEACEFUL, 0, CompanionFeature.CLUMSY, 0, CompanionFeature.EATER, 0, CompanionFeature.PACK, 25, CompanionFeature.HUNTER, 50, CompanionFeature.TRADER, 75, CompanionFeature.WISE), "В мире много профессий, и одна из редких – учёный. Не важно, что именно он исследует, способы выращивания картофеля в северо-восточных заселённых землях или же влияние сбежавших экспериментов на холодные топи в период жаркого и сырого месяцев, всё равно, его, этого исследователя, встретишь не часто. Большинство из них предпочитают заниматься науками в городе, в безопасности, но всё же периодически находятся те, кто готов рискуя жизнью толкать прогресс вперёд, по трактам Пандоры. Такие исследователи с удовольствием примыкают к опытным ходокам, способным защитить их от хищников и бандитов."),
    RAVEN(64, "Ворон", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.ADVENTURER, CompanionDedication.HESITANT, 40, getFeaturesMap(0, CompanionFeature.CANNY, 0, CompanionFeature.DISCREET, 0, CompanionFeature.EATER, 0, CompanionFeature.LAZY, 0, CompanionFeature.FLYER, 0, CompanionFeature.WISE, 50, CompanionFeature.HAWKEYE), "Легендарная птица Пандоры. Ворон обитает повсеместно, но его весьма сложно повстречать, ибо он сторонится цивилизации, предпочитая уединение. Это, без сомнения, самая удивительная из птиц. Вороны умеют говорить, и они мудры. Благодаря тому, что эти крупные пернатые живут сотни лет, они порой способны научить кое-чему и хозяина."),
    ONE_EYED_CRIPPLE(73, "Одноглазый калека", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.EATER, 0, CompanionFeature.TRADER, 0, CompanionFeature.COWARD, 20, CompanionFeature.DRUNKARD, 40, CompanionFeature.PACK, 60, CompanionFeature.CAD, 80, CompanionFeature.WORSHIPPER), "В этом суровом мире многим приходится познать боль и страдания. В Пандоре нередко можно встретить калек, пытающихся выжить, найти лучшую участь, новый дом. Иногда они просят героев взять их с собой, потому и нет ничего странного в том, что встречаются порой ходоки в компании, например, одноглазого калеки."),
    CAPUCHIN_MONKEY(74, "Обезьянка-капуцин", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.LAZY, 0, CompanionFeature.COWARD, 0, CompanionFeature.EATER, 0, CompanionFeature.CUTE, 33, CompanionFeature.PICKPOCKET, 66, CompanionFeature.ROBBER), "Редкая, ласковая и симпатичная обезьянка-капуцин – приятнейший спутник для каждого авантюриста. Не очень-то послушный и трусоватый, капуцин легко обучается приносить всякие блестящие вещи, например, монеты или серьги. Скрасить отдых на привале своему хозяину капуцин считает делом чести: если герой утром обнаруживает второй носок в муравейнике, а ботинок в ближайшем ручье, извлекает осиное гнездо из рюкзака и крысиный хвост из котелка с кашей, значит ночь для маленького друга прошла не зря."),
    SLED_VARAN(58, "Ездовой варан", CompanionRarity.UNCOMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.VALIANT, 50, getFeaturesMap(0, CompanionFeature.SLED, 0, CompanionFeature.CLUMSY, 0, CompanionFeature.COMPLEX, 50, CompanionFeature.FREIGHT), "Стальное тело этой ящерицы, длинное и неповоротливое, абсолютно не приспособлено для боя. У этого конструкта другое назначение – его спина увенчана седлом. Ездовой варан не отличается скоростью, зато не ведает усталости. И, конечно, многих привлекает оригинальность подобного транспортного средства."),
    PONY(65, "Пони", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.HESITANT, 40, getFeaturesMap(0, CompanionFeature.PEACEFUL, 0, CompanionFeature.EATER, 0, CompanionFeature.CUTE, 0, CompanionFeature.LAZY, 0, CompanionFeature.CLUMSY, 0, CompanionFeature.SLED, 50, CompanionFeature.PACK), "Пони – милые лошадки самых разных мастей, встречающиеся по всему миру. Миролюбивый нрав этих животных обеспечил им добрую славу, а их пугливость вызывает умиление. Из-за своего невысокого роста пони особенно востребованы в поселениях гоблинов и дварфов."),
    BLACK_VARAN(57, "Чёрный варан", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.ADVENTURER, CompanionDedication.HESITANT, 40, getFeaturesMap(0, CompanionFeature.POISONER, 0, CompanionFeature.SLOW, 0, CompanionFeature.EATER, 25, CompanionFeature.DEVOURER, 50, CompanionFeature.FIGHTER, 75, CompanionFeature.INDEPENDENT), "Этот большой ящер не слишком послушен из-за своего невысокого интеллекта, но обладает острыми зубами и быстрой реакцией. Укус чёрного варана зачастую ядовит, ведь наибольшая часть его рациона – падаль. Стоит отметить изумительный цвет шкуры этой рептилии, который любят очень многие герои-ходоки и прочие искатели приключений."),
    KITE_CONSTRUCT(60, "Коршун-конструкт", CompanionRarity.UNCOMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BRAVE, 50, getFeaturesMap(0, CompanionFeature.FIGHTER, 0, CompanionFeature.SPARE_PARTS, 0, CompanionFeature.FLYER, 50, CompanionFeature.BODYGUARD), "Собранный из меди, бронзы и золочёной проволоки, коршун-конструкт совсем ненамного превышает размерами обычного, но благодаря стальному клюву способен доставить серьёзные неприятности врагу. Такую птицу сложно создать, поэтому путешественники довольно редко используют в качестве спутников коршунов-конструктов."),
    EAGLE_MESSENGER(59, "Орёл-посланник", CompanionRarity.LEGENDARY, CompanionType.UNCOMMON, Archetype.MAGE, CompanionDedication.HESITANT, 70, getFeaturesMap(0, CompanionFeature.PROMPT, 0, CompanionFeature.HONEST, 0, CompanionFeature.DISCREET, 0, CompanionFeature.FLYER, 0, CompanionFeature.SPIRIT_CONTACT, 33, CompanionFeature.HAWKEYE, 66, CompanionFeature.FIGHTER), "Орлы слишком горды, чтобы поддаваться приручению, но милостивые Хранители порой посылают их духовные воплощения в помощь смертным. Главное достоинство этих волшебных птиц, конечно же, зрение: с высоты своего подоблачного полёта орёл-посланник всегда вовремя заметит опасность и сможет предупредить о ней хозяина."),
    SILVER_OWL(63, "Серебряная сова", CompanionRarity.RARE, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.HESITANT, 50, getFeaturesMap(0, CompanionFeature.HULKY, 0, CompanionFeature.EXPENSIVE, 0, CompanionFeature.COMPLEX, 0, CompanionFeature.FLYER, 50, CompanionFeature.HAWKEYE), "Надёжный, прочный и статусный конструкт – серебряная сова. Магомеханическая птица невелика, чуть больше голубя, но очень красива, благодаря сверкающим на солнце перьям, покрытым узорной вязью."),
    ARCHER(69, "Лучница", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.HESITANT, 50, getFeaturesMap(0, CompanionFeature.EATER, 0, CompanionFeature.FIGHTER, 33, CompanionFeature.HUNTER, 66, CompanionFeature.HAWKEYE), "Самые острые конфликты решаются на длине меча, и обычная женщина тут не поспорит в силе с мужчиной. Так было, есть и будет. Но воин, у которого за спиной есть поддержка стрелка, имеет огромное преимущество перед противником. И вот тут-то, с луком, где важна меткость, а вовсе не крепость рук, женщины ничем не уступают мужчинам. Не стоит удивляться тому, что многие девушки, особенно из народа эльфов, лишаясь кормильцев или не имея их с детства, выходят на широкий тракт и познают опасную жизнь наёмника."),
    HEAVY_DONKEY(66, "Неподъёмный осёл", CompanionRarity.RARE, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.HESITANT, 70, getFeaturesMap(0, CompanionFeature.HULKY, 0, CompanionFeature.COMPLEX, 0, CompanionFeature.SLOW, 0, CompanionFeature.DRAUGHT, 50, CompanionFeature.RAM), "Герои пандорских дорог практически никогда не пользуются обычными мулами, предпочитая им металлических конструктов, более надёжных и менее прихотливых. Те путешественники, которые по каким-то причинам недолюбливают механизмы, выберут другое верховое животное, нежели мула."),
    POWER_KITE(62, "Энергетический коршун", CompanionRarity.EPIC, CompanionType.UNCOMMON, Archetype.MAGE, CompanionDedication.BOLD, 30, getFeaturesMap(0, CompanionFeature.VILE, 0, CompanionFeature.PEACEFUL, 0, CompanionFeature.SPIRIT_CONTACT, 0, CompanionFeature.FLYER, 50, CompanionFeature.PEP), "Сотканный из магической энергии коршун лишён плоти, а потому куда более живуч, чем обычная птица. Разрушить колдовские связи, дающие жизнь этому созданию, весьма сложно. Энергетический коршун прекрасный помощник в пути, но, к сожалению, довольно редкий."),
    WHITE_RAVEN(61, "Белая ворона", CompanionRarity.LEGENDARY, CompanionType.ALIVE, Archetype.ADVENTURER, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.PROMPT, 0, CompanionFeature.FLYER, 0, CompanionFeature.VERY_RARE, 0, CompanionFeature.INSPIRATION, 0, CompanionFeature.EATER, 50, CompanionFeature.HAWKEYE), "Если кого-то пытаются оскорбить, то, бывает, несправедливо обзывают белой вороной. Конечно, вороны-альбиносы встречаются необычайно редко, но ничего отрицательного в них нет. Ходоки знают – это замечательный спутник, ценящий дружбу и доверие. Белая, прекрасная птица на плече героя всегда привлечёт взгляды окружающих."),
    DONKEY(67, "Ослик", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.HESITANT, 40, getFeaturesMap(0, CompanionFeature.OBSTINATE, 0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.DRAUGHT, 0, CompanionFeature.EATER, 0, CompanionFeature.CLUMSY, 0, CompanionFeature.SEDATE, 33, CompanionFeature.SPIRIT_CONTACT, 66, CompanionFeature.HAWKEYE), "Серые ослики распространены по всей Пандоре. Они выносливы, хорошо плодятся, едят немного, неприхотливы и стоят недорого. Все эти плюсы с лихвой перекрывают единственный минус – трудность дрессировки."),
    PILGRIM(72, "Пилигрим", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.ADVENTURER, CompanionDedication.BOLD, 30, getFeaturesMap(0, CompanionFeature.EATER, 0, CompanionFeature.PACK, 33, CompanionFeature.WORSHIPPER, 66, CompanionFeature.HEALER), "Многие странствуют по миру, желая посетить разного рода святыни. Часто пилигримы просят о помощи героев-ходоков. Кто ещё защитит на опасных трактах? За это паломники готовы оказать героям посильную помощь: нести часть вещей, стирать, готовить. Большинство прославленных бродяг соглашаются, во-первых, есть с кем поболтать в дороге, а во-вторых пилигримы постоянно кому-то молятся и за себя и за своих провожатых, что вполне может помочь в самых разных ситуациях."),
    ;

    public final int id;
    public final String name;
    public final CompanionRarity rarity;
    public final CompanionType type;
    public final Archetype archetype;
    public final CompanionDedication dedication;
    public final int health;
    public final Map<CompanionFeature, Integer> features;
    public final String description;

    CompanionSpecies(final int id, final String name, final CompanionRarity rarity, final CompanionType type,
                     final Archetype archetype, final CompanionDedication dedication, final int health,
                     Map<CompanionFeature, Integer> features, final String description) {
        this.id = id;
        this.name = name;
        this.rarity = rarity;
        this.type = type;
        this.archetype = archetype;
        this.dedication = dedication;
        this.health = health;
        this.features = features;
        this.description = description;
    }

    private static Map<CompanionFeature, Integer> getFeaturesMap(final Object... features) {
        if((features == null) || (features.length == 0) || (features.length % 2 == 1)) {
            throw new IllegalArgumentException("Bad features map format");
        }

        final int size = features.length / 2;
        final Map<CompanionFeature, Integer> map = new HashMap<>(size);
        for(int i = 0; i < size; i++) {
            map.put((CompanionFeature) features[i * 2 + 1], (Integer) features[i * 2]);
        }

        return map;
    }

    public int getCode() {
        return id;
    }
    
}
