package com.lonebytesoft.thetaleclient.api.dictionary;

import java.util.HashMap;
import java.util.Map;

/**
 * @author Hamster
 * @since 17.02.2015
 */
public enum CompanionSpecies {

    MECHANICAL_DOG(14, "Механическая собака", CompanionRarity.COMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BRAVE, 40, getFeaturesMap(0, CompanionFeature.FIGHTER, 0, CompanionFeature.SLOW, 0, CompanionFeature.COMPLEX, 33, CompanionFeature.RAM, 66, CompanionFeature.BODYGUARD), "Один из многих «домашних» конструктов – механическая собака. Нет ничего удивительного в том, что магомеханики брали за основу образ всеми любимого животного. Однако полученный результат весьма далёк от ожидаемого: лязгающие, периодически заклинивающиеся механизмы не очень-то похожи на собак, к тому же довольно сложно устроены, что затрудняет их эксплуатацию и ремонт."),
    DWARF_MASTIFF(12, "Дварфский мастиф", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.VALIANT, 50, getFeaturesMap(0, CompanionFeature.HONEST, 0, CompanionFeature.LAZY, 0, CompanionFeature.EATER, 0, CompanionFeature.FIGHTER, 33, CompanionFeature.GOON, 66, CompanionFeature.DEVOURER), "Издалека эту собаку можно принять за медведя. Невероятных размеров пёс с густой тёмно-бурой шерстью имеет грудь, в обхвате почти не уступающей медвежьей, огромную голову с короткой, но смертоносной пастью, толстые мощные лапы, медленный, но уверенный шаг. Горный, так ещё называют эту породу, мастифф был выведен для охраны, охоты и спасательных работ при снежных обвалах. Сложно найти собаку опаснее, сильнее и выносливее, и абсолютно точно не найти породы умней."),
    RAVEN_PERCHERON(40, "Вороной першерон", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 50, getFeaturesMap(0, CompanionFeature.SLED, 0, CompanionFeature.EATER, 33, CompanionFeature.DRAUGHT, 66, CompanionFeature.INDEPENDENT), "Известная повсеместно порода тягловых лошадей заслужила добрую славу. Высокие, с широкой грудью и сильными ногами першероны незаменимы для караванщиков. Вороная же масть, выведенная дварфами – гарантия прекрасной родословной."),
    POLISHED_CHEETAH(18, "Отполированный гепард", CompanionRarity.COMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BRAVE, 30, getFeaturesMap(0, CompanionFeature.FIGHTER, 33, CompanionFeature.BODYGUARD, 66, CompanionFeature.RAM), "Не самая удачная попытка создать полезного конструкта. Тонкий металлический отполированный кот получился быстрым, и это, пожалуй, его единственное достоинство, позволяющее всё же атаковать цель. В остальном это весьма ненадёжный механизм, но, надо признать, достаточно симпатичный."),
    TRAINED_CAT(6, "Дрессированный кот", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.ADVENTURER, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.EATER, 0, CompanionFeature.DEXTEROUS, 0, CompanionFeature.PUNY, 0, CompanionFeature.CUTE, 33, CompanionFeature.INDEPENDENT, 66, CompanionFeature.HAWKEYE), "Довольно редкое явление – дрессированный кот. Кошки плохо поддаются дрессуре, но если всё же удаётся научить кота показывать разные трюки, выполнять команды, то, как правило, зрителям это нравится. Народ умиляется, глядя на забавных животных, и всегда готов подкинуть артисту пару монет на что-нибудь вкусненькое «для милашки»."),
    JAGUAR(17, "Ягуар", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 50, getFeaturesMap(0, CompanionFeature.HONEST, 0, CompanionFeature.LAZY, 0, CompanionFeature.EATER, 0, CompanionFeature.FIGHTER, 33, CompanionFeature.INDEPENDENT, 66, CompanionFeature.GOON), "Этот красивый дикий кот – олицетворение благородства и грации. Мало кому удаётся подчинить себе столь дикого зверя. Но если всё же ягуар начинает слушаться хозяина, привязывается к нему, то счастливому обладателю этого чуда завидуют все."),
    CRAB_EATING_FOX(9, "Майконг", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.HESITANT, 40, getFeaturesMap(0, CompanionFeature.CANNY, 0, CompanionFeature.EATER, 0, CompanionFeature.FIGHTER, 33, CompanionFeature.INDEPENDENT, 66, CompanionFeature.HAWKEYE), "Орки утверждают, что это лиса, некоторые учёные твердят, что майконги – собаки. Как бы там ни было, жители пустынь давно пытаются воспитывать и дрессировать этих животных. Но пока это далеко не всегда удаётся . И всё же многие хотят иметь не просто собаку, а что-нибудь экзотичное, и храбрые, пусть и диковатые, майконги пользуются определённой популярностью."),
    PAPER_STORK(37, "Бумажный аист", CompanionRarity.UNCOMMON, CompanionType.MECH, Archetype.MAGE, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.PIGMEAT, 0, CompanionFeature.PROMPT, 0, CompanionFeature.HAWKEYE, 0, CompanionFeature.FLYER, 50, CompanionFeature.IMPETUOUS), "Стоит ли говорить о хрупкости этого конструкта? Склеенный из ивовых прутиков и бумаги, наделённый весьма слабой магией, аист хорошо выполняет функции наблюдателя, но, увы, недолго. Бумажные птицы столь дёшевы, что порой их покупают, как игрушки для детей, Однако для начинающего ходока, ограниченного в средствах, нет лучшего спутника в дороге."),
    COWRIE_NAG(39, "Каурая кляча", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.VILE, 0, CompanionFeature.PUNY, 0, CompanionFeature.TROTTER, 0, CompanionFeature.EATER, 0, CompanionFeature.COWARD, 33, CompanionFeature.FREIGHT, 66, CompanionFeature.DEXTEROUS), "Ничем не примечательная лошадь. Она неприхотлива, сообразительна. Учитывая цену на это верховое животное, пугливость каурой клячи сложно рассматривать как серьёзный недостаток."),
    COMPOSITE_HEAVY_HORSE(41, "Композитный битюг", CompanionRarity.UNCOMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.VALIANT, 70, getFeaturesMap(0, CompanionFeature.HULKY, 0, CompanionFeature.SLED, 0, CompanionFeature.NOISY, 33, CompanionFeature.DRAUGHT, 66, CompanionFeature.RAM), "Очень надёжный, прочный и грузоподъёмный конструкт. Устройство его таково, что большинство деталей можно делать из разных металлов и даже древесины, поэтому не бывает двух одинаковых композитных битюгов. Эти лошади, как правило, выглядят пёстро и очень разнообразно, что добавляет им некоторой привлекательности."),
    TRAINED_CARACAL(20, "Дрессированный каракал", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 30, getFeaturesMap(0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.CAMOUFLAGE, 0, CompanionFeature.EATER, 0, CompanionFeature.FIGHTER, 33, CompanionFeature.INDEPENDENT, 66, CompanionFeature.DEVOURER), "Только немногие мастера, орки и люди, способны дрессировать этих диких кошек. Секрет воспитания передаётся из поколения в поколение и тщательно оберегается. Но результат, как правило, превосходит все ожидания: красавцы каракалы становятся очень послушными и готовы отдать жизнь за своего хозяина."),
    FRAGILE_LION(23, "Хрупкий лев", CompanionRarity.COMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BRAVE, 30, getFeaturesMap(0, CompanionFeature.FEARFUL, 0, CompanionFeature.GOON, 0, CompanionFeature.SPARE_PARTS, 33, CompanionFeature.RAM, 66, CompanionFeature.BODYGUARD), "Своеобразный, жутковато выглядящий конструкт. Недолговечен из-за подбора материалов, из которых создан, и всё же он очень и очень неплох в деле. Хрупкость каркаса льва полностью компенсируется его мощными лапами и острыми зубами, которыми этот кот может уничтожить почти любого противника. Конструкт непопулярен, но тот, кто знает толк в боях, всегда оценит опасность соперника, обладающего этим смертоносным магомеханизмом."),
    SHAGGY_DOG(10, "Лохматый пёс", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 30, getFeaturesMap(0, CompanionFeature.CANNY, 0, CompanionFeature.PEACEFUL, 0, CompanionFeature.COWARD, 0, CompanionFeature.LAZY, 0, CompanionFeature.INDEPENDENT, 0, CompanionFeature.EATER, 33, CompanionFeature.FIGHTER, 66, CompanionFeature.HAWKEYE), "Беспородные собаки есть в каждой деревне, кроме эльфийской, разумеется. Умные, преданные, отлично дрессируемые собаки навсегда останутся лучшими друзьями и дома, и в путешествии."),
    ORC_HOUND(13, "Орочья гончая", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 40, getFeaturesMap(0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.EATER, 0, CompanionFeature.LAZY, 0, CompanionFeature.FIGHTER, 0, CompanionFeature.DEXTEROUS, 33, CompanionFeature.HAWKEYE, 66, CompanionFeature.BODYGUARD), "Орочья гончая весьма популярна у охотников и отличается легкостью в разведении.У этой породы множество достоинств: ум, преданность хозяину, длинные быстрые лапы, превосходный нюх. Стоит также отметить невысокую цену, которую орки-заводчики просят за рыжих с подпалинами щенков."),
    ALBINO_PANTHER(30, "Пантера-альбинос", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BRAVE, 50, getFeaturesMap(0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.GLUTTONOUS, 0, CompanionFeature.FEARFUL, 0, CompanionFeature.HAWKEYE, 0, CompanionFeature.IMPETUOUS, 25, CompanionFeature.FIGHTER, 50, CompanionFeature.BODYGUARD, 75, CompanionFeature.GOON), "Нет сомнения, что пантера-альбинос – один из самых редких зверей во всей Пандоре. Огромная белоснежная кошка с пугающими красными глазами обладает агрессивным и своенравным характером. При этом она очень легко привязывается к хозяину, и, как утверждают специалисты, сложно найти более преданного спутника. Этот факт в сочетании с выдающейся силой, чутким слухом и прекрасным ночным зрением делает пантеру-альбиноса завидным помощником любому искателю приключений."),
    OCELOT_CONSTRUCT(22, "Оцелот-конструкт", CompanionRarity.UNCOMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.VALIANT, 30, getFeaturesMap(0, CompanionFeature.FIGHTER, 0, CompanionFeature.EXPENSIVE, 0, CompanionFeature.GNAWER, 0, CompanionFeature.COMPLEX, 33, CompanionFeature.GOON, 66, CompanionFeature.RAM), "Дикие кошки, пожалуй, самые частые вдохновители магомехаников. Силу и грацию этих мистических животных крайне редко удаётся передать механизмам, но в случае с оцелотом-конструктом мы видим превосходный результат. Невысокая прочность – единственный недостаток, легко компенсируемый скоростью, мощностью и надёжностью исполнения вложенных охранных задач."),
    STEEL_FOX(15, "Стальная лиса", CompanionRarity.UNCOMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BOLD, 40, getFeaturesMap(0, CompanionFeature.PACK, 0, CompanionFeature.DEXTEROUS, 33, CompanionFeature.BODYGUARD, 66, CompanionFeature.FIGHTER), "Один из самых популярных и элегантных конструктов. Весьма удобен в эксплуатации, с ним редко возникают проблемы технического характера, но это не самый сильный помощник в бою. Стальную лису редко можно встретить в продаже – их изготавливают лучшие магомеханики и только на заказ."),
    POISONOUS_LYNX(19, "Рысь-ядомор", CompanionRarity.COMMON, CompanionType.MECH, Archetype.ADVENTURER, CompanionDedication.BRAVE, 30, getFeaturesMap(0, CompanionFeature.POISONER, 0, CompanionFeature.SPARE_PARTS, 0, CompanionFeature.EXPENSIVE, 33, CompanionFeature.FIGHTER, 66, CompanionFeature.RAM), "Весьма интересный механический помощник. Конструкт создаётся с использованием дорогостоящей магии, которая делает когти стальной рыси отравленными. Очень популярен у героев и прочих искателей приключений. Немаловажно, что в случае его поломки всегда можно выгодно продать запчасти."),
    SPARKLING_ONCILLA(32, "Сверкающая онцилла", CompanionRarity.UNCOMMON, CompanionType.UNCOMMON, Archetype.ADVENTURER, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.STUBBORN, 0, CompanionFeature.CANNY, 0, CompanionFeature.DISCREET, 0, CompanionFeature.FIGHTER, 25, CompanionFeature.SPIRIT_CONTACT, 50, CompanionFeature.WORSHIPPER, 75, CompanionFeature.BODYGUARD), "Мелкая бестелесная кошка. Её не перепутать с обычным хищником благодаря искрящейся шерсти, сверкающей даже при свете дня. Если коснуться этого существа, то рука пройдёт сквозь тело онциллы, не встретив препятствия. Такие создания очень непослушны, но всё же могут принести немалую пользу своему хозяину, магически атакуя его противников."),
    CLAY_BLACK_BEAR(33, "Глиняный барибал", CompanionRarity.COMMON, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.VALIANT, 50, getFeaturesMap(0, CompanionFeature.CLUMSY, 0, CompanionFeature.RAM, 50, CompanionFeature.GOON), "Медведь барибал – сам по себе опасный хищник, и уж тем более опасен конструкт, созданный по его образу и подобию, но не чувствующий ни боли, ни страха. Конечно, глина – один из самых непрочных материалов для создания магомеханических спутников, однако данный проект оказался успешным, а полученные экземпляры весьма надёжными и функциональными."),
    FIGHTER_MERCENARY(8, "Воин-наёмник", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BRAVE, 40, getFeaturesMap(0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.DEXTEROUS, 0, CompanionFeature.GLUTTONOUS, 0, CompanionFeature.FIGHTER, 25, CompanionFeature.PACK, 50, CompanionFeature.DRUNKARD, 75, CompanionFeature.GOON), "В Пандоре много наёмников. Среди них встречаются как новички, так и матёрые ветераны. Последних, конечно же, немного и все они, за редким исключением, состоят на уважаемой службе: охраняют советников, поддерживают безопасность на трактах. Но порой всё же можно увидеть настоящего воина-наёмника в компании с героем-ходоком. Эти бродяги иногда тоже готовы платить за помощь."),
    TAMED_COUGAR(27, "Ручной кугуар", CompanionRarity.UNCOMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BRAVE, 30, getFeaturesMap(0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.EATER, 0, CompanionFeature.CAMOUFLAGE, 0, CompanionFeature.DEXTEROUS, 0, CompanionFeature.HAWKEYE, 50, CompanionFeature.FIGHTER), "Этот редкий вид пумы обитает в тёплых невысоких горах и предгорьях. Кугуары редко нападают на путников, так как не выходят к трактам и поселениям, при этом они удивительно легко приручаются. Рыжие кошки хоть и не выделяются размерами или силой, но довольно агрессивны. Они стали бы, вероятно, крайне популярными спутниками многих героев, если бы встречались в природе чаще. Но, к сожалению, численность их невелика, а размножение в неволе пока не имеет успеха."),
    WHITE_BEAR(34, "Белый медведь", CompanionRarity.RARE, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 70, getFeaturesMap(0, CompanionFeature.FIGHTER, 0, CompanionFeature.FEARFUL, 0, CompanionFeature.GLUTTONOUS, 0, CompanionFeature.GNAWER, 20, CompanionFeature.DEVOURER, 40, CompanionFeature.GOON, 60, CompanionFeature.INDEPENDENT, 80, CompanionFeature.RAM), "Один из самых редких медведей, как живых, так и механических. Этот огромный зверь обитает на далёком севере, повстречать его крайне сложно. Белый медведь – страшный и могучий хищник, умный, выносливый и неприхотливый. Тот, кто сумеет с ним подружиться, получит непревзойдённого помощника."),
    PIEBALD_NAG(38, "Пегая кляча", CompanionRarity.COMMON, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 30, getFeaturesMap(0, CompanionFeature.PEACEFUL, 0, CompanionFeature.LAZY, 0, CompanionFeature.SLED, 0, CompanionFeature.EATER, 0, CompanionFeature.PIGMEAT, 33, CompanionFeature.PACK, 66, CompanionFeature.INDEPENDENT), "В мире много лошадей, дорогих и не очень, скаковых и упряжных, но есть и такие, которые всем знакомы, их не спутаешь ни с какой другой. Самая обычная лошадь, имеющаяся в любом поселении – это пегая кляча. У этого животного всего понемногу и всё в меру: стать, выносливость, престиж и… цена."),
    CLAY_LEOPARD(31, "Глиняный барс", CompanionRarity.RARE, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BRAVE, 50, getFeaturesMap(0, CompanionFeature.COMPLEX, 0, CompanionFeature.FIGHTER, 50, CompanionFeature.RAM), "Глиняный барс весьма распространён по всей Пандоре. По большому счёту этот конструкт весьма хорош, но трудно выделить какие-то характерные именно для него положительные качества. Средней полезности помощник для средних по сложности дел, однако, крупный хищник, пусть и изготовленный из дешёвой глины, смотрится прекрасно и создаёт неплохой имидж хозяину."),
    GINGER_TROTTER(42, "Игреневый рысак", CompanionRarity.RARE, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BRAVE, 50, getFeaturesMap(0, CompanionFeature.PEACEFUL, 0, CompanionFeature.PACK, 0, CompanionFeature.EATER, 0, CompanionFeature.RARE, 33, CompanionFeature.LIGHTFOOTED, 66, CompanionFeature.INDEPENDENT), "Прекрасной породы и красивой масти конь один из лучших спутников любому герою. Игреневые рысаки ценятся по всей Пандоре за миролюбивый нрав и скорость. У этих скакунов длинные ноги, тонкая шея и лёгкий бег, а также, что очень важно для путешественников, они не пугливы и не впадают в панику даже при виде хищника."),
    FOG_WOLF(16, "Туманный волк", CompanionRarity.RARE, CompanionType.UNCOMMON, Archetype.MAGE, CompanionDedication.BRAVE, 60, getFeaturesMap(0, CompanionFeature.OBSTINATE, 0, CompanionFeature.VILE, 0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.WORSHIPPER, 25, CompanionFeature.FIGHTER, 50, CompanionFeature.REGENERATION, 75, CompanionFeature.INSPIRATION), "Посланник из мира Хранителей. Весьма своенравное создание, будто сотканное из тумана, чуть светящегося во тьме. Быстрый, колдовской, с горящими жёлтыми глазами туманный волк вызывает уважение к своему обладателю."),
    COMPLEX_LEOPARD(24, "Мудрёный леопард", CompanionRarity.RARE, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.HESITANT, 50, getFeaturesMap(0, CompanionFeature.COMPLEX, 0, CompanionFeature.FIGHTER, 50, CompanionFeature.GOON), "Яркий пример того, как конструкт “не получился”. Создатели этого тяжёлого металлического хищника наверняка хотели достичь совершенно иного результата, но, как говорится, перемудрили. В итоге получился крепкий, мощный, но очень сложный в управлении и ремонте конструкт-охранник. Впрочем, производитель готов продавать своё творение по весьма сходной цене."),
    WHITE_TIGER(26, "Белый тигр", CompanionRarity.EPIC, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.HEROIC, 70, getFeaturesMap(0, CompanionFeature.HONEST, 0, CompanionFeature.DISCREET, 0, CompanionFeature.GLUTTONOUS, 0, CompanionFeature.GOON, 0, CompanionFeature.CAMOUFLAGE, 20, CompanionFeature.INDEPENDENT, 40, CompanionFeature.RAM, 60, CompanionFeature.DEVOURER, 80, CompanionFeature.BODYGUARD), "Многие мечтают хотя бы просто увидеть белого тигра – одну из легенд Пандоры. Счастливец тот, кто сможет стать другом этому могучему и прекрасному зверю, воплотившему в себе дух свободы и благородства. Белый тигр крупнее своих сородичей, его очень сложно повстречать и почти невозможно подчинить."),
    SLOW_BEAR(36, "Медлительный кадьяк", CompanionRarity.EPIC, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BRAVE, 60, getFeaturesMap(0, CompanionFeature.COMPLEX, 0, CompanionFeature.EXPENSIVE, 0, CompanionFeature.FIGHTER, 0, CompanionFeature.SLOW, 33, CompanionFeature.RAM, 66, CompanionFeature.GOON), "Дорогостоящий, сложно устроенный конструкт, хороший помощник в приключениях. Он силён и послушен, внушительно выглядит. И всё же многие скажут, что этот металлический медведь “на любителя”, ведь у него есть существенный недостаток – медлительность, и нередкие задержки в пути немного портят репутацию кадьяка."),
    BLACK_CAT(7, "Чёрная кошка", CompanionRarity.RARE, CompanionType.ALIVE, Archetype.ADVENTURER, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.STUBBORN, 0, CompanionFeature.EATER, 0, CompanionFeature.CHARMING, 0, CompanionFeature.IMPETUOUS, 0, CompanionFeature.COWARD, 25, CompanionFeature.HAWKEYE, 50, CompanionFeature.SPIRIT_CONTACT, 75, CompanionFeature.INDEPENDENT), "Чёрным кошкам все расы во все времена приписывают необычные свойства. Ничего удивительного, в них и правда есть что-то мистическое. Стоит заглянуть в опаловые глаза, и становится ясно: они видят то, что нам не дано узреть никогда. Когда ты смотришь на чёрную кошку, знай – ей известно большее, гораздо большее, нежели нам."),
    EARED_SERVAL(21, "Ушастый сервал", CompanionRarity.RARE, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.VALIANT, 50, getFeaturesMap(0, CompanionFeature.PACK, 0, CompanionFeature.DEXTEROUS, 33, CompanionFeature.RAM, 66, CompanionFeature.FIGHTER), "Конструкт, что называется, на любителя. Многим нравится его внешний вид, очень напоминающий живого кота. Ценят также надёжность механизма, удивительную при столь небольших размерах. Ушастых сервалов сложно приобрести, их изготавливают в незначительных количествах. Это чудо магомеханики всегда легко узнать по длинным лапам и обязательным большим ушам, несущим сугубо декоративное назначение."),
    REINDEER(5, "Северный олень", CompanionRarity.LEGENDARY, CompanionType.ALIVE, Archetype.MAGE, CompanionDedication.BRAVE, 60, getFeaturesMap(0, CompanionFeature.CONSCIENTIOUS, 0, CompanionFeature.EATER, 0, CompanionFeature.TROTTER, 0, CompanionFeature.SPECIAL, 20, CompanionFeature.INDEPENDENT, 40, CompanionFeature.SPIRIT_CONTACT, 60, CompanionFeature.PACK, 80, CompanionFeature.INSPIRATION), "Северный олень – красивое и гордое животное. Он никогда и никому не покоряется. Есть, конечно слухи об орках кочевниках, живущих в снежных пустынях и сумевших приручить оленей, но это не более, чем слухи. Северный олень – достаточно большой, чтобы возить орка на спине, совершенно дикий и своенравный зверь."),
    ASTRAL_PANTHER(29, "Астральная пантера", CompanionRarity.LEGENDARY, CompanionType.UNCOMMON, Archetype.ADVENTURER, CompanionDedication.HESITANT, 60, getFeaturesMap(0, CompanionFeature.PROMPT, 0, CompanionFeature.HONEST, 0, CompanionFeature.AGGRESSIVE, 0, CompanionFeature.WORSHIPPER, 20, CompanionFeature.GOON, 40, CompanionFeature.REGENERATION, 60, CompanionFeature.ENERGETIC, 80, CompanionFeature.RAM), "Прозрачно-чёрная, словно вылитая из дорогого стекла; стремительная, но неторопливая; агрессивная, но полностью послушная – астральная пантера грациозна и великолепна, она истинный дар Хранителя своему подопечному. Этот благородный волшебный зверь – прекрасный и верный спутник героя."),
    VILLAGE_BLACKSMITH(1, "Деревенский кузнец", CompanionRarity.LEGENDARY, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.BOLD, 40, getFeaturesMap(0, CompanionFeature.FIGHTER, 0, CompanionFeature.SPECIAL, 0, CompanionFeature.DRUNKARD, 0, CompanionFeature.EATER, 33, CompanionFeature.PACK, 66, CompanionFeature.GOON), "Деревенские – народ крепкий, а уж кузнецы и подавно. Крепкие, сухие, выносливые мастера скобяных дел, если их разозлить, могут быть весьма опасны. Удар кузнечного молота, на наковальне правящий металл, с телом врага способен сотворить чистое месиво. К тому же, не стоит забывать, что некоторые кузнецы делают оружие и порой неплохо этим оружием владеют."),
    GREY_PUMA(25, "Серая пума", CompanionRarity.EPIC, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.VALIANT, 50, getFeaturesMap(0, CompanionFeature.LAZY, 0, CompanionFeature.EATER, 0, CompanionFeature.IMPETUOUS, 0, CompanionFeature.FIGHTER, 20, CompanionFeature.HAWKEYE, 40, CompanionFeature.DEVOURER, 60, CompanionFeature.GOON, 80, CompanionFeature.INDEPENDENT), "Редкий вид дикой горной кошки. Этот опасный хищник обладает великолепным слухом и зрением и предупредит хозяина об опасности, правда, если захочет. Собственно, непокорность серой пумы – главный аргумент противников приручения этих животных."),
    WOLFHOUND(11, "Волкодав", CompanionRarity.LEGENDARY, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.VALIANT, 60, getFeaturesMap(0, CompanionFeature.CONSCIENTIOUS, 0, CompanionFeature.FEARFUL, 0, CompanionFeature.EATER, 0, CompanionFeature.HAWKEYE, 0, CompanionFeature.DEXTEROUS, 25, CompanionFeature.FIGHTER, 50, CompanionFeature.INDEPENDENT, 75, CompanionFeature.SPIRIT_CONTACT), "Волкодавы – это особенные собаки. Серые лохматые псы, огромные и страшные, обладают мощными челюстями, острым слухом и полным, абсолютным бесстрашием. Их вывели у людей для охраны скота от волков, но порода уже давным-давно пользуется популярностью повсюду. Волкодавы охраняют дворы, караваны, детей и склады. Это поистине уникальные и незаменимые собаки."),
    PALADIN(4, "Паладин", CompanionRarity.LEGENDARY, CompanionType.ALIVE, Archetype.ADVENTURER, CompanionDedication.BRAVE, 50, getFeaturesMap(0, CompanionFeature.GOON, 0, CompanionFeature.EATER, 0, CompanionFeature.SPECIAL, 25, CompanionFeature.HEALER, 50, CompanionFeature.WORSHIPPER, 75, CompanionFeature.EXORCIST), "Есть много способов служения Богам, и один из них – вступить в какой-нибудь орден паладинов, чтущих Добро и Порядок. Эти воинствующие священники по мере сил, порой весьма внушительных, истребляют нежить, демонов и прочие порождения Тьмы... К сожалению, они не столь крепки, как герои-ходоки, и потому живут недолго... Но ярко!"),
    SUMMONED_FOSSA(28, "Призванная фосса", CompanionRarity.LEGENDARY, CompanionType.UNCOMMON, Archetype.MAGE, CompanionDedication.BOLD, 60, getFeaturesMap(0, CompanionFeature.VILE, 0, CompanionFeature.PEACEFUL, 0, CompanionFeature.SPIRIT_CONTACT, 0, CompanionFeature.CAMOUFLAGE, 20, CompanionFeature.FIGHTER, 40, CompanionFeature.HAWKEYE, 60, CompanionFeature.PEP, 80, CompanionFeature.BODYGUARD), "У фоссы, мелкого хищника, имеется двойник в нематериальном мире. Это существо магического происхождения может оказать большую помощь своему обладателю благодаря изрядной хитрости и особой связи с Хранителем. Призванная фосса крупнее живого прообраза, гораздо умнее его и обладает подлыми повадками. При этом она до конца готова защищать хозяина, не чувствуя ни страха, ни боли."),
    ORPHAN(2, "Сиротинушка", CompanionRarity.LEGENDARY, CompanionType.ALIVE, Archetype.WARRIOR, CompanionDedication.HESITANT, 30, getFeaturesMap(0, CompanionFeature.STUBBORN, 0, CompanionFeature.CUTE, 0, CompanionFeature.PUNY, 0, CompanionFeature.GLUTTONOUS, 0, CompanionFeature.SPECIAL, 33, CompanionFeature.PICKPOCKET, 66, CompanionFeature.PACK), "В деревне нередко можно встретить детей-сирот, которым помогают кто чем может. Таких ребят зовут почти ласково – сиротинушка. Они не столь сильно обижены на мир, как городские беспризорники, но всё же некоторые мечтают уйти из деревни... Только вот редко кто берёт их с собой."),
    TEMPLE_GUARD(3, "Храмовый страж", CompanionRarity.LEGENDARY, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.BOLD, 50, getFeaturesMap(0, CompanionFeature.COMPLEX, 0, CompanionFeature.FIGHTER, 0, CompanionFeature.FEARFUL, 0, CompanionFeature.EXPENSIVE, 0, CompanionFeature.SPECIAL, 33, CompanionFeature.BODYGUARD, 66, CompanionFeature.RAM), "У служителей различных храмов свои тайны, которые они ревностно стерегут, в чём им помогают не только шпионы, воины и деньги. Храмовники вполне успешно используют магию, в том числе магомеханизмы. Один из таких наиболее редких и легендарных конструктов – храмовый страж. Он является изобретением поклонников некоего доброго божества. Это мощный и крайне опасный боевой магомеханизм, вооружённый двумя булавами и осадным арбалетом, вмонтированным в стальной корпус. В целом же храмовый страж напоминает металлическую курицу ростом с гоблина."),
    GOLD_BEAR(35, "Золотой шатун", CompanionRarity.LEGENDARY, CompanionType.MECH, Archetype.WARRIOR, CompanionDedication.VALIANT, 40, getFeaturesMap(0, CompanionFeature.COMPLEX, 0, CompanionFeature.EXPENSIVE, 0, CompanionFeature.GOON, 0, CompanionFeature.VERY_RARE, 25, CompanionFeature.PACK, 50, CompanionFeature.RAM, 75, CompanionFeature.SLED), "Пожалуй, самый претенциозный из всех возможных конструктов. Груда золота и золочёной стали, имеющая форму медведя с огромными когтями, конечно же, внушает трепет и уважение, но при этом вызывает странное чувство. Золото – не самый прочный металл, да и драгоценные камни глаз многим кажутся излишеством, ведь подошёл бы и простой горный хрусталь. И уж совсем необычно выглядит на спине у конструкта инкрустированное золотом седло, которое крепят некоторые умельцы."),
    ;

    public final int id;
    public final String name;
    public final CompanionRarity rarity;
    public final CompanionType type;
    public final Archetype archetype;
    public final CompanionDedication dedication;
    public final int health;
    public final Map<CompanionFeature, Integer> features;
    public final String description;

    private CompanionSpecies(final int id, final String name, final CompanionRarity rarity, final CompanionType type,
                             final Archetype archetype, final CompanionDedication dedication, final int health,
                             Map<CompanionFeature, Integer> features, final String description) {
        this.id = id;
        this.name = name;
        this.rarity = rarity;
        this.type = type;
        this.archetype = archetype;
        this.dedication = dedication;
        this.health = health;
        this.features = features;
        this.description = description;
    }

    private static Map<CompanionFeature, Integer> getFeaturesMap(final Object... features) {
        if((features == null) || (features.length == 0) || (features.length % 2 == 1)) {
            throw new IllegalArgumentException("Bad features map format");
        }

        final int size = features.length / 2;
        final Map<CompanionFeature, Integer> map = new HashMap<>(size);
        for(int i = 0; i < size; i++) {
            map.put((CompanionFeature) features[i * 2 + 1], (Integer) features[i * 2]);
        }

        return map;
    }

    public int getCode() {
        return id;
    }
    
}
